#Carta(id_carta, nome_carta, nro_edicao, descricao, #id_deck, id_natureza, id_tipo_carta)
INSERT INTO Carta
	VALUES
    (null, 'Dragao de Fogo da Terra Negra', 1, 'Um dragão que habita nas profundezas da escuridão, sua vulnerabilidade está em sua visão fraca', 1, 3, 1),
    (null, 'Mago Negro', 1, 'O mago supremo em termos de ataque e defesa.', 1, 3, 1),
    (null, 'Mago do Tempo', 1, 'Uma vez por turno: você pode jogar uma moeda e chamá-la, se você acertar, destrua todos os monstros que seu oponente controla. Se você errar, destrua tantos monstros que você controla quanto possível, e se você sofrer dano igual a metade do ATK total que aqueles monstros destruídos tinham no campo.', 1, 3, 6),
    (null, 'Guardiao Celta', 1, 'Um elfo que aprendeu a empunhar uma espada, ele confunde os inimigos com ataques rápidos como relâmpagos.', 1, 3, 7),
    (null, 'Gaia o Cavaleiro Impetuoso', 1, 'Um cavaleiro cujo cavalo viaja mais rápido que o vento. Sua carga de batalha é uma força a ser considerada.', 1, 3, 8),
    (null, 'Rei Caveira', 1, 'Um demônio com poderes sombrios para confundir o inimigo. Entre os monstros Fiend-Type, este monstro possui uma força considerável. (Esta carta é sempre tratada como uma carta Archfiend)', 1 , 3, 7),
    (null, 'Kuriboh', 1, 'Descarte esta carta da sua mão. Faça o Dano de Batalha infligido aos seus Pontos de Vida por 1 dos monstros do seu oponente. Você só pode usar este efeito durante a Fase de Batalha do seu oponente.', 1 , 3, 7),
	(null, 'Dragao Alado, Guardiao da Fortaleza', 1, 'Um dragão comumente encontrado guardando fortalezas nas montanhas, seu ataque característico é um mergulho arrebatador do nada.', 1, 3, 9),
    (null, 'Braco Direito de O Proibido', 1, 'Um braço direito proibido selado por magia, Quem quebrar este selo conhecerá o poder infinito.', 1, 3, 11),
	(null, 'Braco Esquerdo de O Proibido', 1, 'Um braço esquerdo proibido selado por magia, Quem quebrar este selo conhecerá o poder infinito.', 1, 3, 9),
	
    (null, 'Perna Direita de O Proibido', 1, 'Uma perna direita proibida selado por magia, Quem quebrar este selo conhecerá o poder infinito.', 2, 3, 8),
    (null, 'Perna Esquerda de O Proibido', 1, 'Uma perna esquerda proibida selado por magia, Quem quebrar este selo conhecerá o poder infinito.', 2, 3, 8),
    (null, 'Maldicao do Dragao', 1, 'Um dragão perverso que usa as forças das trevas para executar um ataque poderoso.', 2, 3, 1),
    (null, 'Castor Guerreiro', 1, 'O que esta criatura não tem em tamanho compensa na defesa ao lutar na pradaria', 2, 3, 10),
    (null, 'Jovem Touro Guerreiro', 1, 'Um monstro Bull frequentemente encontrado na floresta, ele carrega monstros inimigos com um par de chifres mortais.', 2, 3, 11),
    (null, 'Demonio Selvagel', 1, 'Um pequeno demônio brincalhão que espreita no escuro, esperando para atacar um inimigo incauto.', 2, 3, 1),
    (null, 'Demonio de Chifre', 1, 'Um Demonio que  ataca seus inimigos com seu chifre na cabeca', 2, 3, 6),
    (null, 'Elfa Mistica', 1, 'Um elfo delicado que não tem ofensas mas tem uma defesa terrível apoiada por poder místico', 2, 3, 10),
    (null, 'Imperador Cruel', 1, 'Com um machado em cada mão, este monstro causa dano pesad', 2, 3, 6),
    (null, 'O Presa de Prata', 1, 'Um lobo da neve que é bonito aos olhos, mas absolutamente cruel na batalha', 2, 3, 6),
    
    (null, 'Dragao Koumori', 1, 'Um dragão cruel cuspidor de fogo cuja chama maligna corrompe as almas de suas vítimas.', 3, 3, 1),
    (null, 'Soldado Gigante de Pedra', 1, 'Um guerreiro gigante feito de pedra. Um soco desta criatura tem resultados impressionantes.', 3, 3, 1),
    (null, 'Sangan', 1, 'Quando este card for enviado do campo para o cemitério: adicione 1 monstro com 1500 ou menos de ATK do seu Deck à sua mão.', 3, 3, 7),
    (null, 'Sábio Negro', 1, 'Não pode ser Normal Summon/Set. Deve primeiro ser Invocado por Invocação-Especial (da sua mão ou Deck) ao oferecer como Tributo 1 "Mago ​​Negro" Imediatamente após aplicar o efeito do Mago do Tempo no qual você chamou a moeda também. Quando Invocado por Invocação-Especial desta forma: Adicione 1 Card de Magia do seu Deck à sua mão.', 3, 3, 10),
    (null, 'Tartaruga Catapulta', 1, 'Uma vez por turno: você pode oferecer como Tributo 1 monstro; inflija dano ao seu oponente igual a metade do ATK do monstro oferecido como Tributo no campo.', 3, 3, 10),
    (null, 'Exodia, O Proibido', 1, 'Quando voce possui todas as partes do corpo de O Proibido, ao adicionar esta carta a sua mão você vence o duelo.', 3, 3, 7),
    (null, 'Soldado do Lustro Negro', 1, 'Você pode Invocar este card por Invocação-Ritual com "Ritual do Lustro Negro".', 3, 3, 1),
    (null, 'Mago do Caos das Trevas', 1, 'Você pode Invocar este card por Invocação-Ritual com "Ritual de Magia Negra".', 3, 3, 9),
    (null, 'Dragao Caveira Negro', 1, '"Summoned Skull" + "Red-Eyes B. Dragon"', 3, 3, 9),
    (null, 'Gaia, o Campeao do Dragao', 1, '"Gaia the Fierce Knight" + "Curse of Dragon"', 3, 3, 1),
    
    (null, 'Cavaleiro Mestre dos Dragoes', 1, '"Soldado do Lustro Negro" + "Dragão Supremo de Olhos Azuis". Este monstro não pode ser Special Summoned exceto por Fusion Summon. Esta Carda ganha 500 ATK para cada outro monstro do Tipo Dragão que você controla.Magic Ritual".', 4, 3, 10),
    (null, 'Anulacao de Magia', 1, 'Selecione 1 Card de Magia no campo e destrua-o. Se a carta selecionada for Set, pegue e semeie a carta. Se for um Spell Card, ele é destruído. Se for um Card de Armadilha, devolva-o à sua posição original.', 4, 1, 1),
    (null, 'Polimerizacao', 1, 'Fusion Summon 1 Fusion Monster do seu Extra Deck, usando monstros da sua mão ou do seu lado do campo como Fusion Materials.', 4, 2, 4),
    (null, 'Espadas da Luz Reveladora', 1, 'Vire todos os monstros virados para baixo no lado do campo do seu oponente com a face para cima. Esta carta permanece virada para cima no campo por 3 do turno do seu oponente. Enquanto esta carta permanecer virada para cima no campo, seu oponente não pode declarar um ataque.', 4, 2, 2),
    (null, 'Cartolas Mágicas', 1, 'Durante a Fase de Batalha do seu oponente: escolha 2 cartas que não sejam de Monstro do seu Deck e 1 monstro que você controla. Embaralhe essas 3 cartas e coloque-as no campo em Posição de Defesa. As 2 cartas escolhidas do seu Deck de hora são tratadas como Monstros Normais (ATK 0 / DEF 0) e são destruídas no final da Fase de Batalha.', 4, 2, 2),
    (null, 'Monstro que Renasce', 1, 'Escolha 1 monstro no Cemitério de qualquer duelista: Invoque-o por Invocação-Especial.', 4, 1, 2),
    (null, 'Recuperacao de Monstro', 1, 'Escolha 1 monstro no Unite 1 de qualquer jogador dos seus próprios monstros no seu lado do campo e na sua mão com o seu Deck e depois embaralhe-o. Compre do baralho o mesmo número de cartas que estavam na sua mão. (Você não pode ativar esta carta se tiver uma carta do oponente em sua mão).: Invoque-a por Invocação-Especial.', 4, 1, 1),
    (null, 'Livro das Artes Secretas', 1, 'Um monstro do tipo Invocador equipado com esta carta aumenta seu ATK e DEF em 300 pontos.', 4, 2, 2),
    (null, 'Controle Cerebral', 1, 'Pague 800 Pontos de Vida e, em seguida, escolha 1 monstro com a face para cima que seu oponente controla: tome o controle desse alvo até a Fase Final.', 4, 2, 2),
    (null, 'Folego da Luz', 1, 'Destrua todos os monstros Rock-Type virados para cima no campo.', 4, 2, 4),
    
    (null, 'Buraco Negro', 1, 'Destroi todos os monstros em capo', 5, 2, 4),
    (null, 'Chifre do Unicornio', 1, 'O monstro equipado ganha 700 ATK e DEF. Quando este card for enviado do campo para o Cemitério: devolva-o ao topo do Deck.field.', 5, 2, 3),
    (null, 'Flecha Destruidora de Magia', 1, 'Destrua todos os Cards de Magia virados para cima que seu oponente controla. Para cada Carta de Magia destruída, cause 500 de dano ao seu oponente.', 5 , 1, 5),
    (null, 'Ritual do Lustro Negro', 1, 'Esta carta é usada para Ritual Summon "Black Luster Soldier" você também deve oferecer como Tributo monstros da sua mão ou campo cujo total de níveis seja igual a 8 ou mais.', 5 , 2, 2),
    (null, 'Ritual de Magia Negra', 1, 'Quando um monstro do oponente declarar um ataque: escolha o monstro atacante; negar o ataque, o fim da Fase de Batalha.', 5, 2, 3),
    (null, 'Libertar Almas', 1, 'Escolha até 5 cards em qualquer cemitério(s); bani-los', 5, 1, 5),
    (null, 'Caixa Mistica', 1, 'Escolha 1 monstro que seu oponente controla e 1 monstro que você controla; destrua o primeiro alvo, então dê o controle do segundo alvo ao seu oponente.', 5 , 1, 5),
    (null, 'Multiplicar', 1, 'Tribute 1 "Kuriboh" com a face para cima; Special Summon o maior número possível de "Kuriboh Tokens" (Fiend-Type/DARK/LEVEL 1/ATK 300/DEF 200) em Posição de Defesa. Esses Tokens não podem ser oferecidos como Tributo para uma Invocação-Tributo.', 5 , 2, 2),
    (null, 'Makiu, a Nevoa Mistica', 1, 'Escolha 1 monstro "Summoned Skull" virado para cima ou Thunder Type virado para cima que você controla; destrua todos os monstros que seu oponente controla com DEF menor ou igual ao ATK daquele monstro. Você não pode conduzir sua Fase de Batalha no turno em que ativar esta carta.', 5, 1, 2),
    (null, 'O Olho da Verdade', 1, 'Enquanto esta carta permanecer virada para cima no campo, seu oponente deve mostrar sua mão. Seu oponente aumenta seus Pontos de Vida em 1000 pontos durante cada uma de suas Fases de Apoio se ele tiver um Card de Magia na mão.', 5, 1, 2),
    
    (null, 'Dragao Branco de Olhos Azuis', 1, 'Este lendário dragão é um poderoso motor de destruição, praticamente invencível, muito poucos enfrentaram essa criatura incrível e viveram para contar a história.', 6, 3, 8),
    (null, 'Saggi, o Palhaco das Trevas', 1, 'Este palhaço aparece do nada e executa movimentos muito estranhos para evitar ataques inimigos.', 6, 3, 7),
    (null, 'Imperador Cruel', 1, 'Com um machado em cada mão, este monstro causa dano pesado.', 6, 3, 1),
    (null, 'Touro Guerreiro', 1, 'Um monstro com tremendo poder, destrói os inimigos com um golpe de seu machado.', 6, 3, 1),
    (null, 'Centauro Mistico', 1, 'Meio homem e meio cavalo, este monter é conhecido por sua extrema velocidade.', 6, 3, 9),
    (null, 'Gigante Hitotsu-Me', 1, 'Um gigante caolho com braços grossos e poderosos feitos para desferir golpes punitivos.', 6, 3, 6),
    (null, 'Ryu-Kishin Potencializado', 1, 'Uma gárgula encantada pelos poderes das trevas. Garras muito afiadas fazem dele um oponente digno.', 6, 3, 6),
    (null, 'La Jinn o Genio Mistico da Lampada', 1, 'Um gênio da lâmpada que está à disposição de seu mestre.', 6, 3, 7),
    (null, 'Aqua Madoor', 1, 'Um mago das águas que conjura uma parede líquida para esmagar qualquer inimigo que se oponha a ele.', 6, 3, 9),
    (null, 'Juiz', 1, 'Este guerreiro empunhando o clube luta até o fim e nunca se renderá.', 6, 3, 7),
    
    (null, 'Grappler', 1, 'Uma cobra desonesta com um corpo grosso que envolve um monstro inimigo e espreme a vida dele.', 7, 3, 9),
    (null, 'Mestre das Armadilhas', 1, 'VIRE: Selecione 1 Card de Armadilha no campo e destrua-o. Se a carta selecionada estiver definida, pegue e veja a carta. Se for um Card de Armadilha, ele é destruído. Se for um Card de Magia, devolva-o à sua posição original.' , 7, 3, 11),
    (null, 'Cyber Jarra', 1, 'VIRE: Destrua todos os monstros no campo e, em seguida, ambos os duelistas revelam as 5 primeiras cartas de seus Decks e, em seguida, Invoque por Invocação-Especial todos os monstros revelados de Nível 4 ou inferior com a face para cima em Posição de Ataque ou com a face para baixo em Posição de Defesa e adicione quaisquer cartas restantes ao sua mão, (Se um dos jogadores tiver menos de 5 cartas em seu Deck, revele o maior número possível.)', 7 , 1, 5),
    (null, 'Senhor dos Dragoes', 1, 'Monstros do Tipo Dragão no campo não podem ser escolhidos como alvo de efeitos de cartas.', 7, 3, 9),
    (null, 'Perseguidor', 1, 'Um monstro formado pelas almas vingativas daqueles que faleceram em batalha', 7, 1, 2),
    (null, 'Barreira Ilusoria', 1, 'Se este card for atacado por um monstro, após o cálculo de dano: devolva esse monstro para a mão', 7, 1, 2),
    (null, 'Centauro Furioso', 1, '"Boi de Batalha" + "Cavaleiro Místico"', 7, 3, 10),
    (null, 'Ultimate Dragao Branco de Olhos Azuis', 1, '"Blue-Eyes White Dragon" + "Blue-Eyes White Dragon" + "Blue-Eyes White Dragon"', 7, 3, 10),
    (null, 'Anulacao de Magia', 1, 'Selecione 1 Card de Magia no campo e destrua-o. Se a carta selecionada estiver definida, pegue e veja a carta. Se for um Spell Card, ele é destruído. Se for um Card de Armadilha, devolva-o à sua posição original.', 7, 1, 1),
    (null, 'Feitico Sombra', 1, 'Ative esta carta escolhendo 1 monstro virado para cima que seu oponente controla; perde 700 ATK, também não pode atacar ou mudar sua posição de batalha. Quando ela deixar o campo, destrua esta carta.', 7, 1, 1),
    
    (null, 'Dadiva da Elfa Mistica', 1, 'Aumente seus pontos de vida em 300 pontos para cada monstro no campo.', 8, 2, 3),
    (null, 'Flauta para Invocacao de Dragoes', 1, 'Invoque por Invocação-Especial até 2 monstros do Tipo Dragão da sua mão. "Senhor de D." deve estar em campo para ativar e resolver este efeito.', 8, 2, 1),
    (null, 'Controle Mesmerico', 1, 'Durante o próximo turno do seu oponente após você ativar esta carta, seu oponente não pode mudar as posições de batalha dos monstros, exceto com um efeito de carta.', 8, 2, 1),
    (null, 'Negativacao de Ataque', 1, 'Quando um monstro do oponente declarar um ataque: escolha o monstro atacante; negue o ataque e encerre a Fase de Batalha.', 8, 2, 2),
    (null, 'Gerador de Energia Negativa', 1,'Selecione 1 monstro DARK virado para cima que você controla. Triplique seu ATK original.', 8, 2, 4),
    (null, 'Virus Esmagador de Cartas', 1, 'Tribute 1 monstro DARK com ATK 1000 ou menos; seu oponente não sofre dano até o final do próximo turno após esta carta resolver, além disso, você olha para a mão do seu oponente e todos os monstros que ele controla, e se isso acontecer, destrua os monstros entre eles com 1500 ou mais de ATK, então seu oponente pode destruir até 3 monstros com 1500 ou mais de ATK em seu Deck.', 8 , 2, 3),
    (null, 'Impedir Defesa', 1, 'Ative apenas quando um monstro do oponente for mudado para a Posição de Defesa. Mude todos os monstros que seu oponente controla para a Posição de Ataque.', 8, 2, 2),
    (null, 'Lampada Antiga', 1, 'Durante sua Fase Principal: você pode Invocar por Invocação-Especial "La jinn, o Gênio Místico da Lâmpada" da sua mão. Esta carta deve estar virada para cima no campo para ativar e resolver este efeito. Antes do cálculo de dano, se este card estiver sendo atacado por um monstro do oponente e estava com a face para baixo no início da Etapa de Dano: você pode escolher 1 monstro que seu oponente controla, exceto o monstro atacante, o monstro atacante o ataca em vez', 8 , 2, 4),
    (null, 'Monstro que Renasce', 1, 'Escolha 1 monstro no cemitério de qualquer duelista; Invoque-o especialmente.', 8, 2, 3),
    (null, 'Polimerizacao', 1, 'Fusion Summon 1 Fusion Monster do seu Extra Deck, usando monstros da sua mão ou do seu lado do campo como Fusion Materials.', 8, 2, 2),
    
    (null, 'Dragao Branco do Mundo da Fantasia', 1, 'Não pode ser Normal Summon/Set. Deve primeiro ser Invocado por Invocação-Especial (da sua mão) ao oferecer 2 monstros como Tributo, enquanto você controla "Mundo das Ferramentas". Não pode atacar no turno em que for Invocado por Invocação-Especial. Você deve pagar 500 PV para declarar um ataque com este monstro. Se "Toon World" no campo for destruído, destrua este card.', 9, 3, 7),
    (null, 'Sereia do Mundo da Fantasia', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 9, 3, 7),
    (null, 'Rei Caveira do Mundo da Fantasia', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 9, 3, 7),
    (null, 'Jacaré do Mundo da Fantasia', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 9, 3, 7),
    (null, 'Coelhinho Negro', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 9, 3, 7),
    (null, 'Dragao Papagaio', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 9, 3, 7),
    (null, 'Amante Feliz', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 9, 3, 7),
    (null, 'Mago Ilusionista Sem Rosto', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 9, 3, 10),
    (null, 'Doma, o Anjo do Silencio', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 9, 3, 10),
    (null, 'Vespa Assassina', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 9, 3, 10),
    
    (null, 'Garota Arqueira Vermelha', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 10, 3, 11),
    (null, 'Ryu-Ran', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 10, 3, 1),
    (null, 'Idolo dos Mil Olhos', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 10, 3, 1),
    (null, 'Ilusionista de Olhos Negros', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 10, 3, 1),
    (null, 'Jigen Bakudan', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 10, 3, 11),
    (null, 'Flautista de Dragoes', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 10, 3, 7), 
    (null, 'Mascara das Trevas', 1,'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 10, 3, 1),
    (null, 'Cegueira de Mil Olhos', 1,'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 10, 3, 1),
    (null, 'Abdicacao', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 10, 3, 7),
    (null, 'Mundo da Fantasia', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 10 , 2, 3),
    
    (null, 'Gerador de Energia Negativa', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 11 , 1, 5),
    (null, 'Doppleganger', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 11, 2, 1),
    (null, 'Ritual de Ilusao Negra', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 11, 1, 2),
    (null, 'Olho da Ilusao', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 11 , 1, 5),
    (null, 'Palacio Brilhante', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 11, 2, 1),
    (null, 'Campo de Forca Neutralizante de Magia', 1,'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 11, 2, 1),
    (null, 'Olho da Gorgona', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 11 , 1, 5),
    (null, 'A Profecia', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 11, 1, 2),
    (null, 'Jarra de Captura de Dragoes', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 11, 2, 1),
    (null, 'Lagrimas da Sereia', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 11, 1, 2),
    
    (null, 'Inseto Primario', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 12, 3, 1),
    (null, 'Gokibore', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 12, 3, 1),
    (null, 'Besouro Hercules', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 12, 3, 1),
    (null, 'Kamakiriman', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 12, 3, 1),
    (null, 'Vespa Assassina', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 12, 3, 1),
    (null, 'Casula de Evolucao', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 12, 3, 6),
    (null, 'Larga de Mariposa', 1,'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 12, 3, 6),
    (null, 'Grande Mariposa', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 12, 3, 6),
    (null, 'Armadura com Canhao Laser', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 12, 2, 3),
    (null, 'Armadura de Inseto com Canhao Laser', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 12, 2, 3),
    
    (null, 'Lady Harpia', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 13, 3, 1),
    (null, 'Feiticeira das Sombras', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 13, 3, 1),
    (null, 'Dragao Mascote da Harpia', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 13, 3, 8),
    (null, 'Irmãs da Lady Harpia', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 13, 3, 8),
    (null, 'Anulacao de Magia', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 13, 1, 5),
    (null, 'Cyber Escudo', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 13, 1, 5),
    (null, 'Sombra dos Olhos', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 13, 2, 1),
    (null, 'Espanador de Penas da Harpia', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 13, 3, 8),
    (null, 'Egotista Elegante', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 13, 3, 8),
    (null, 'Parede Espelhada', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 13, 1, 5),
    
    (null, 'Luz da Amizade', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 14, 2, 3),
    (null, 'Maga da Fe', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 14, 3, 8),
    (null, 'Pequeno Anjo', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 14 , 3, 1),
    (null, 'Fada Madrinha', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 14, 3, 8),
    (null, 'Amante Feliz', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 14, 2, 3),
    (null, 'Luz do Duende', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 14, 1, 5),
    (null, 'Folego da Luz', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 14, 2, 3),
    (null, 'Anulacao de Magia', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 14, 1, 5),
    (null, 'Arco e Flecha de Prata', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 14, 2, 3),
    (null, 'Waboku', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 14, 3, 8),
    
    (null, 'Dama da Fe', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 15, 3, 7),
    (null, 'Magico de Cartola Branca', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 15, 3, 7),
    (null, 'Inseto Comedor de Homem', 1,'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 15, 3, 1),
    (null, 'Choque Morfina', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 15, 1, 2),
    (null, 'Amante Feliz', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 15, 3, 11),
    (null, 'Doma o Anjo do Silencio', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 15, 3, 1),
    (null, 'Lagarto Eletrico', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 15, 3, 11),
    (null, 'Mascara da Escuridao', 1,'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 15, 1, 5),
    (null, 'Troca de Coracao', 1,'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 15, 1, 5),
    (null, 'Apenas Sobremesas', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 15, 1, 5),
    
    (null, 'Dragao Negro de Olhos Vermelhos', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 16, 3, 6),
    (null, 'Dragao Serpente das Trevas', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 16, 3, 1),
    (null, 'Dragao de Duas Cabecas King Rex', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 16, 3, 1),
    (null, 'Megazowler', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 16, 3, 7),
    (null, 'Dragao Cauda Assassina', 1,'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 16, 3, 7),
    (null, 'Trakodon', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 16, 3, 1),
    (null, 'Uraby', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 16, 3, 1),
    (null, 'Dragao Rastejante', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 16, 3, 1),
    (null, 'Domador de Monstros', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 16, 3, 1),
    (null, 'Guardiao do Portao', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 16, 3, 7),
    
    (null, 'Sanga do Trovao', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 17, 3, 1),
    (null, 'Vampiro das Sombras', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 17, 3, 1),
    (null, 'Parede das Sombras', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 17, 1, 2),
    (null, 'Labirinto Magico', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 17, 1, 2),
    (null, 'Remover Armadilha', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 17, 1, 2),
    (null, 'Paredes do Labirinto', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 17, 1, 1),
    (null, 'Lombriga da Masmorra', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 17, 1, 1),
    (null, 'Kazejin', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 17, 3, 1),
    (null, 'Suijin', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 17, 3, 1),
    (null, 'Tanque do Labirinto', 1,'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 17, 1, 2),
    
    (null, 'Fortalecimento', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 18, 2, 3),
    (null, 'Riryoku', 1,'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..' , 18, 3, 8),
    (null, 'Jirai Gumo', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 18 , 3, 1),
    (null, 'Metalzoa', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 18 , 3, 1),
    (null, 'Zoa', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 18 , 3, 1),
    (null, 'Aranha Lancadora', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 18, 3, 8),
    (null, 'Guardiao do Portal', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 18, 3, 8),
    (null, 'Ferramenta Antiga', 1,'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..' , 18, 2, 3),
    (null, 'Caca-Niquels', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 18, 2, 3),
    (null, 'Elefante Garnecia', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 18, 3, 1),
    
    (null, 'Giganto', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 19 , 3, 1),
    (null, 'Dragao Canhao', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 19 , 3, 1),
    (null, 'Esfera Explosiva', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 19, 1, 1),
    (null, 'Maquina de Pendulo', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 19, 3, 11),
    (null, 'Sabre Cortador', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 19, 3, 8),
    (null, '7 Completo', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 19, 2, 2),
    (null, 'Maquina do Tempo', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 19, 2, 3),
    (null, 'Forca Magica Metalica', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 19, 3, 11),
    (null, 'Estripador de Cartas', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 19, 3, 8),
    (null, 'Quimera Negra', 1, 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..', 19 , 3, 1);